repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.2.0'
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: double-quote-string-fixer

- repo: https://github.com/pycqa/isort
  rev: '5.10.1'
  hooks:
  - id: isort
    args:
    - --profile=black
    files: ^backend/

- repo: https://github.com/psf/black
  rev: '22.3.0'
  hooks:
  - id: black
    args:
    - --skip-string-normalization
    files: ^backend/
