repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.2.0'
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/asottile/pyupgrade
  rev: "v2.32.1"
  hooks:
  - id: pyupgrade
    args: ["--py310-plus"]

- repo: https://github.com/hadialqattan/pycln
  rev: "v1.3.2"
  hooks:
  - id: pycln
    args:
    - --config=backend/pyproject.toml
    - --all

- repo: https://github.com/pycqa/isort
  rev: '5.10.1'
  hooks:
  - id: isort
    args:
    - --profile=black
    files: ^backend/

- repo: https://github.com/psf/black
  rev: '22.3.0'
  hooks:
  - id: black
    args:
    - --skip-string-normalization
    files: ^backend/

- repo: https://github.com/pycqa/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8
    name: flake 8 (src)
    args:
    - --max-line-length=88
    # D106 Missing docstring in public nested class
    # D401 First line should be in imperative mood
    - --extend-ignore=D106,D401
    - --extend-ignore=D
    - --extend-immutable-calls=Body,Depends,Field,Path,Query
    additional_dependencies:
    - flake8-bugbear
    - flake8-docstrings
    files: ^backend/sonouno_server/

- repo: https://github.com/pycqa/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8
    name: flake 8 (tests)
    args:
    # E501 Line too long
    - --extend-ignore=D, E501
    files: ^backend/tests/
