[tool.poetry]
name = "sonouno_server"
version = "0.1.0"
description = "A scientific data sonification platform."
authors = ["Pierre Chanial <pierre.chanial@apc.in2p3.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.72.0"
beanie = "^1.8.12"
fastapi-jwt-auth = "^0.5.0"
bcrypt = "^3.2.0"
uvicorn = "^0.17.0"
pydantic = {extras = ["email"], version = "^1.9.0"}

[tool.poetry.dev-dependencies]
python-decouple = "^3.5"
pytest = "^6.2.5"
asgi-lifespan = "^1.0.1"
pytest-asyncio = "^0.17.1"
httpx = "^0.21.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
