# Pull base image
FROM python:3.10-slim

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code/

# Install Poetry
RUN apt-get update && apt-get install -y curl
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | POETRY_HOME=/opt/poetry POETRY_PREVIEW=1 python \
 && cd /usr/local/bin \
 && ln -s /opt/poetry/bin/poetry \
 && poetry config virtualenvs.create false

# Copy poetry.lock* in case it doesn't exist in the repo
COPY ./pyproject.toml ./poetry.lock* /code/

# Allow installing dev dependencies to run tests
RUN poetry install --no-root
RUN poetry run pip install fastapi-mail==1.0.2

# Make some libraries available in the transform interpretor.
# This is a temporary solution, code execution should be performed in a container,
# not in the server's process.
RUN bash -c "poetry run pip install requests pandas astropy"

# For development, Jupyter remote kernel, Hydrogen
# Using inside the container:
# jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888
ARG INSTALL_JUPYTER=false
RUN bash -c "if [ \"${INSTALL_JUPYTER}\" == 'true' ] ; then pip install jupyterlab ; fi"

COPY . /code

ENV PYTHONPATH=/code
