version: "3"

volumes:
  sonouno-db-data:

networks:
  backend-network:
    driver: bridge

services:

  sonouno-server:
    image: ${SONOUNO_SERVER_IMAGE:-sonounoserver}:${SONOUNO_SERVER_TAG:-latest}
    container_name: sonouno-server
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      - SENTRY_DSN=https://nowhere.com
      - PROJECT_NAME=sonoUno Server
      - MONGO_INITDB_USERNAME
      - MONGO_INITDB_PASSWORD
      - MONGO_INITDB_DATABASE
      - SALT
    ports:
      - "8001:8001"
    networks:
      - backend-network
    build:
      context: ../backend
      args:
        - INSTALL_DEV
    command: bash -c "/code/scripts/prepare-app.sh && uvicorn sonouno_server.main:app --root-path=${ROOTPATH:-/} --port 8001 --host 0.0.0.0 --reload"

  mongodb:
    image: ${SONOUNO_SERVER_IMAGE:-sonounoserver}-mongo:${SONOUNO_SERVER_TAG:-latest}
    container_name: mongodb
    restart: always
    hostname: mongodb
    volumes:
      - sonouno-db-data:/data/db/
#      - ../mongodb-logs/:/var/log/mongodb/
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_USERNAME
      - MONGO_INITDB_PASSWORD
    ports:
      - "27017:27017"
    networks:
      - backend-network
    command: ["-f", "/etc/mongod.conf"]
    build:
      context: ../mongodb

  mongo-express:
    image: ${SONOUNO_SERVER_IMAGE:-sonounoserver}-mongo-express:${SONOUNO_SERVER_TAG:-latest}
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
    networks:
      - backend-network
    build:
      context: ../mongo-express
