version: "3"

services:

  sonouno-server:
    image: ${SONOUNO_SERVER_IMAGE:-esap-db}:${SONOUNO_SERVER_TAG:-latest}
    container_name: sonouno-server
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      - SENTRY_DSN=https://nowhere.com
      - PROJECT_NAME=sonoUno Server
      - TEST_MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
    build:
      context: ../backend
      args:
        INSTALL_DEV: ${INSTALL_DEV:-false}
    command: bash -c "/code/scripts/prepare-app.sh && uvicorn sonouno_server.main:app --root-path=${ROOTPATH:-/} --port 8001 --host 0.0.0.0 --reload"
    #command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    ports:
      - "8001:8001"
    networks:
      - backend-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    hostname: mongodb
    volumes:
      - ../mongodb/mongod.conf:/etc/mongod.conf
      - ../mongodb/initdb.d/:/docker-entrypoint-initdb.d/
      - ../mongodb-data/:/data/db/
#      - ../mongodb-logs/:/var/log/mongodb/
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_USERNAME
      - MONGO_INITDB_PASSWORD
    ports:
      - "27017:27017"
    networks:
      - backend-network
    command: ["-f", "/etc/mongod.conf"]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ../mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
